### PR TITLE
Resubmit cancelled/deleted jobs

### LINKED ISSUE #26: Allow resubmitting cancelled/unsuccessful jobs
We could use the same message banner on the page edit view that currently displays the "This translation is managed by Smartling" message but, when the latest translation job for the page is cancelled/deleted show a message to indicate that and include a button to press that will submit the job again: "The latest Smartling job for this translation was {cancelled/deleted}. [Resubmit to Smartling]"

### PR DESCRIPTION
**Pull request by zerolab**
Fixes #26

- adds a view to "retry" cancelled or deleted jobs. The retry is more "create a new job" as the API doesn't have anything in this regard
- while the template uses a form, didn't go the full Django form way as we don't need additional validation
- uses a separate view rather then the ModelViewSet CopyView because of various hoops and rabbit holes that introduces

To-Do:
- [x] add additional checks
- [x] link to the view from the translation page message
- [x] retry view tests (permissions, post)
- ~stretch: look at surfacing cancellation reason in the report, if possible~ could not find a sensible way to do this

### CODE REVIEW

**Comment by stevejalim** [comment]
Heya @zerolab - not chasing you, but if you want me to take a look at this now, do let me know. Don't want you to be blocked waiting for review from me

**Comment by zerolab** [comment]
🤦‍♂️ I was so convinved I've pinged you to take this for a test. Please do.
Will push the test today/tomorrow

**Comment by stevejalim** [comment]
Test driven locally and it's _lovely_ to use. Thank you for this @zerolab - I'm sure it will help me recover well from any process-related footguns I cause :)

**Review by stevejalim — APPROVED** [review]
That's an r+ from me!

Thanks for this addition @zerolab - we really appreciate it and it'll be very useful!

**Comment by zerolab** [comment]
argh, did not get the notification and re-requested your review after you reviewd it.
Will merge and submit the description callback PR (somehow missed that) and I think that is all on the list

**Pull request merged**
